{
 "title": "Pizza Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "requestsPerMinute_ratio{source=\"jwt-pizza-service\"}"
    },
    {
     "expr": "getRequestsPerMinute_ratio{source=\"jwt-pizza-service\"}"
    },
    {
     "expr": "putRequestsPerMinute_ratio{source=\"jwt-pizza-service\"}"
    },
    {
     "expr": "postRequestsPerMinute_ratio{source=\"jwt-pizza-service\"}"
    },
    {
     "expr": "deleteRequestsPerMinute_ratio{source=\"jwt-pizza-service\"}"
    }
   ]
  },
  {
   "title": "Authentication Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "successfulAuthAttemptsPerMinute_ratio{source=\"jwt-pizza-service\"}"
    },
    {
     "expr": "failedAuthAttemptsPerMinute_ratio{source=\"jwt-pizza-service\"}"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "activeUsers_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "endpointLatency_milliseconds{source=\"jwt-pizza-service\", percentile=\"mean\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "averageEndpointLatency_milliseconds{source=\"jwt-pizza-service\"}"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pizzaRevenuePerMinute_USD{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza creation latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pizzaCreationLatency_milliseconds{source=\"jwt-pizza-service\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpuUsage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pizzasSoldPerMinute_ratio{source=\"jwt-pizza-service\"}"
    },
    {
     "expr": "pizzaCreationFailuresPerMinute_ratio{source=\"jwt-pizza-service\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memoryUsage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}